apiVersion: apps/v1
kind: Deployment
metadata:
  name: brahma-gateway
  labels:
    app: brahma-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brahma-gateway
  template:
    metadata:
      labels:
        app: brahma-gateway
    spec:
      containers:
        - name: brahma-gateway
          image: brahma-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: brahma-config
            - secretRef:
                name: brahma-secret

---
apiVersion: v1
kind: Service
metadata:
  name: brahma-gateway
spec:
  type: NodePort
  selector:
    app: brahma-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880