# === HTTP SETTINGS ===
quarkus.http.port=8082

# === DATABASE SETTINGS (PostgreSQL) - DEFAULT DATASOURCE ===
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=brahma
quarkus.datasource.password=brahma123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/brahma

# === HIBERNATE ORM SETTINGS - DEFAULT UNIT ===
# заглушим вывод sql
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.bind-parameters=true
# Добавь эту строку, чтобы отключить конфликт JSON-сериализации
quarkus.hibernate-orm.mapping.format.global=ignore

# === GATEWAY CLIENT (REST Client) ===
quarkus.rest-client.gateway-client.url=http://localhost:8080

# === OPENAPI / SWAGGER UI ===
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# === QUTE TEMPLATES ===
quarkus.qute.suffixes=html

# === LOGGING ===
quarkus.log.level=INFO
quarkus.log.category."com.example.webui".level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c{2} --- %m%n