# HTTP Port
quarkus.http.port=8080

# === ????????? ????-?????? ?????????????? ? dev ?????? ===
quarkus.kafka.devservices.enabled=false
quarkus.datasource.devservices.enabled=false

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=brahma
quarkus.datasource.password=brahma123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/brahma

# Kafka
quarkus.kafka.bootstrap-servers=localhost:9092
mp.messaging.outgoing.registration-topic.connector=smallrye-kafka
mp.messaging.outgoing.registration-topic.topic=terminal.registration
mp.messaging.outgoing.registration-topic.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Health
quarkus.smallrye-health.root-path=/q/health
